version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh /start.sh
    environment:
      - NODE_ENV=development
    ports:
      - 3333:3333
    volumes:
      - ./:/home/service/server/
      - node_modules:/home/service/server/node_modules/

volumes:
  node_modules: